spring.datasource.url=jdbc:postgresql://localhost:5432/book-api-dispence
spring.datasource.username=postgres
spring.datasource.password=root_12*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8087

logging.level.org.hibernate=DEBUG
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
management.endpoints.web.exposure.include=*