spring.application.name=spring-config-book
server.port=8084
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.profiles.active=native

# Gestione ZipKim
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
# spring.config.import=optional:file:.env[.properties]

# Integrazione Git
# spring.cloud.config.server.git.uri=""
# spring.cloud.config.server.git.username=raff-E12
# spring.cloud.config.server.git.password=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
# spring.cloud.config.server.git.clone-on-start=true
# spring.cloud.config.server.git.default-label=main

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.config.enabled=true
spring.cloud.config.server.native.search-locations=\
  classpath:/config/book-services/,\
  classpath:/config/orders-services/,\
  classpath:/config/book-rating/,\
  classpath:/config/book-users-services/

info.app.nome=Config-Services
info.app.versione=1.1.3
info.app.descrizione=Servizio di Gestione Configurazione Microservizi