CREATE TABLE IF NOT EXISTS "libri" (
	"id" INTEGER NOT NULL,
	"titolo" VARCHAR(200) NOT NULL,
	"autore" VARCHAR(100) NOT NULL,
	"editore" VARCHAR(100),
	"anno_pubblicazione" INTEGER CHECK("[object Object]" > 1000 AND "[object Object]" <= 2026),
	"isbn" VARCHAR(13) UNIQUE,
	"categoria" VARCHAR(50) DEFAULT 'Narrativa',
	"num_copie" INTEGER DEFAULT 1 CHECK("[object Object]" > 0),
	"disponibile" INTEGER DEFAULT 1 CHECK("[object Object]" >= 0),
	"posizione_scaffale" VARCHAR(20),
	"note" TEXT,
	"prezzo" DECIMAL(10,2) NOT NULL CHECK("[object Object]" > 0),
	"trashed" BOOLEAN DEFAULT false,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ordini" (
	"id" INTEGER NOT NULL,
	"prezzo_totale" DECIMAL(10,2) CHECK("[object Object]" >= 0),
	"ordinato" BOOLEAN DEFAULT false,
	"id_utente" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "checkout" (
	"id" INTEGER NOT NULL,
	"ordine_id" INTEGER NOT NULL,
	"libro_id" INTEGER NOT NULL,
	"libro_prezzo" DECIMAL(10,2) NOT NULL CHECK("[object Object]" > 0),
	"quantita" INTEGER NOT NULL DEFAULT 1 CHECK("[object Object]" > 0),
	"prezzo_subtotale" DECIMAL(10,2) NOT NULL CHECK("[object Object]" > 0),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "recensioni" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"libro_id" INTEGER,
	"descrizione" VARCHAR(271) DEFAULT 'Vuoto',
	"voto" INTEGER DEFAULT 0,
	"check" BOOLEAN DEFAULT false,
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "utenti" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome_completo" VARCHAR(256) DEFAULT 'Vuoto',
	"email" VARCHAR(273) UNIQUE DEFAULT 'Vuoto',
	"passowrd" VARCHAR(264) DEFAULT 'Vuoto',
	"role" VARCHAR(255) DEFAULT 'Vuoto',
	"verified" BOOLEAN DEFAULT false,
	PRIMARY KEY("id")
);

INSERT INTO utenti (nome_completo, email, passowrd, role, verified)
VALUES
  ('Mario Rossi',    'mario.rossi@email.com',    'hashed_password_1', 'ADMIN', true),
  ('Lucia Bianchi',  'lucia.bianchi@email.com',  'hashed_password_2', 'USER',  true),
  ('Carlo Verdi',    'carlo.verdi@email.com',     'hashed_password_3', 'USER',  false),
  ('Anna Esposito',  'anna.esposito@email.com',  'hashed_password_4', 'USER',  true);

ALTER TABLE "checkout"
ADD FOREIGN KEY("ordine_id") REFERENCES "ordini"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "checkout"
ADD FOREIGN KEY("libro_id") REFERENCES "libri"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "libri"
ADD FOREIGN KEY("id") REFERENCES "recensioni"("libro_id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "ordini"
ADD FOREIGN KEY("id_utente") REFERENCES "utenti"("id")
ON UPDATE CASCADE ON DELETE CASCADE;