CREATE TABLE IF NOT EXISTS "libri" (
	"id" INTEGER NOT NULL,
	"titolo" VARCHAR(200) NOT NULL,
	"autore" VARCHAR(100) NOT NULL,
	"editore" VARCHAR(100),
	"anno_pubblicazione" INTEGER CHECK("[object Object]" > 1000 AND "[object Object]" <= 2026),
	"isbn" VARCHAR(13) UNIQUE,
	"categoria" VARCHAR(50) DEFAULT 'Narrativa',
	"num_copie" INTEGER DEFAULT 1 CHECK("[object Object]" > 0),
	"disponibile" INTEGER DEFAULT 1 CHECK("[object Object]" >= 0),
	"posizione_scaffale" VARCHAR(20),
	"note" TEXT,
	"prezzo" DECIMAL(10,2) NOT NULL CHECK("[object Object]" > 0),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ordini" (
	"id" INTEGER NOT NULL,
	"prezzo_totale" DECIMAL(10,2) CHECK("[object Object]" >= 0),
	"ordinato" BOOLEAN DEFAULT false,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "checkout" (
	"id" INTEGER NOT NULL,
	"ordine_id" INTEGER NOT NULL,
	"libro_id" INTEGER NOT NULL,
	"libro_prezzo" DECIMAL(10,2) NOT NULL CHECK("[object Object]" > 0),
	"quantita" INTEGER NOT NULL DEFAULT 1 CHECK("[object Object]" > 0),
	"prezzo_subtotale" DECIMAL(10,2) NOT NULL CHECK("[object Object]" > 0),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "recensioni" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"libro_id" INTEGER,
	"descrizione" VARCHAR(271) DEFAULT 'Vuoto',
	"voto" INTEGER DEFAULT 0,
	"check" BOOLEAN DEFAULT false,
	PRIMARY KEY("id")
);



ALTER TABLE "checkout"
ADD FOREIGN KEY("ordine_id") REFERENCES "ordini"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "checkout"
ADD FOREIGN KEY("libro_id") REFERENCES "libri"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "libri"
ADD FOREIGN KEY("id") REFERENCES "recensioni"("libro_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;