
services:
  postgres:
      image: postgres:16
      container_name: book-postgres
      environment:
        POSTGRES_DB: bookdb
        POSTGRES_USER: bookuser
        POSTGRES_PASSWORD: bookpassword
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - book-net
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U bookuser -d bookdb"]
        interval: 10s
        timeout: 5s
        retries: 5

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: book-zipkin
    ports:
      - "9411:9411"
    networks:
      - book-net

  eureka-server:
    image: notification-service:latest
    container_name: book-eureka
    ports:
      - "8761:8761"
    networks:
      - book-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  config-server:
    image: book-config-server:latest
    container_name: book-config-server
    ports:
      - "8084:8084"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - book-net
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
 
  book-services:
    build: .
    container_name: book-services
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookdb
      SPRING_DATASOURCE_USERNAME: bookuser
      SPRING_DATASOURCE_PASSWORD: bookpassword
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - book-net
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_started

networks:
  book-net:
    driver: bridge
 
volumes:
  postgres_data: