spring.application.name=discovery-client-services
server.port=8761

# Eureka Server Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logging Configuration (optional)
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO

# Gestione ZipKim
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*


