spring.application.name=book-services-users
spring.profiles.active=dev
server.port=8087

spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=spring-config-book
spring.config.import=optional:configserver:http://localhost:8084

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
logging.level.org.hibernate.orm.results.loading=WARN