
spring.cloud.gateway.server.webmvc.routes[0].id=book-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api-book/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/api-book/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[0].filters[1]=CircuitBreaker=name=bookService,fallbackUri=forward:/api/fallback/book

spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api-orders/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/api-orders/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[1].filters[1]=CircuitBreaker=name=orderService,fallbackUri=forward:/api/fallback/order

spring.cloud.gateway.server.webmvc.routes[2].id=book-rating
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api-rating/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/api-rating/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[2].filters[1]=CircuitBreaker=name=bookRatingService,fallbackUri=forward:/api/fallback/book-rating

resilience4j.circuitbreaker.instances.bookService.register-health-indicator=true
resilience4j.circuitbreaker.instances.orderService.register-health-indicator=true
resilience4j.circuitbreaker.instances.bookRatingService.register-health-indicator=true