spring.application.name=orders-services
server.port=8082
spring.profiles.active=dev

spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=spring-config-book
spring.config.import=optional:configserver:http://localhost:8084

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
logging.level.org.hibernate.orm.results.loading=WARN

# Gestione di Implemetazione
resilience4j.circuitbreaker.instances.orders-services.register-health-indicator=true
resilience4j.circuitbreaker.instances.orders-services.sliding-window-size=3
resilience4j.circuitbreaker.instances.orders-services.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.orders-services.failure-rate-threshold=30
resilience4j.circuitbreaker.instances.orders-services.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.orders-services.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.orders-services.event-consumer-buffer-size=10

# Gestione Rate-Limiter (Limite Chiamate)
resilience4j.ratelimiter.instances.orders-services.limit-for-period=3
resilience4j.ratelimiter.instances.orders-services.limit-refresh-period=10s
resilience4j.ratelimiter.instances.orders-services.timeout-duration=0s

# Gestione Retry (Rintento del servizio)
resilience4j.retry.instances.orders-services.max-attempts=3
resilience4j.retry.instances.orders-services.wait-duration=2s
resilience4j.retry.instances.orders-services.retry-exceptions=java.io.IOException,java.util.concurrent.TimeoutException
resilience4j.retry.instances.orders-services.ignore-exceptions=java.lang.IllegalArgumentException

# Gestione Kafka al livello di Producers
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.retry.backoff.ms=1000

spring.kafka.producer.retries=10
spring.kafka.producer.acks=all
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.linger.ms=1