spring.application.name=book-gateway-services
server.port=8089
spring.profiles.active=dev

spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=spring-config-book
spring.config.import=configserver:http://localhost:8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


