spring.application.name=gateway-services
server.port=8089
spring.profiles.active=dev

spring.cloud.config.discovery.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.gateway.server.webmvc.enabled=true
spring.cloud.config.import-check.enabled=false

management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*

# Rotte del Gateway
spring.cloud.gateway.server.webmvc.routes[0].id=book-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api-book/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/api-book/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[0].filters[1]=CircuitBreaker=name=bookService,fallbackUri=forward:/api/fallback/book

spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api-orders/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/api-orders/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[1].filters[1]=CircuitBreaker=name=orderService,fallbackUri=forward:/api/fallback/order

spring.cloud.gateway.server.webmvc.routes[2].id=book-rating
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api-rating/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/api-rating/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[2].filters[1]=CircuitBreaker=name=bookRatingService,fallbackUri=forward:/api/fallback/book-rating

# Book-Service
resilience4j.circuitbreaker.instances.bookService.register-health-indicator=true
resilience4j.circuitbreaker.instances.bookService.sliding-window-size=5
resilience4j.circuitbreaker.instances.bookService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.bookService.failure-rate-threshold=10
resilience4j.circuitbreaker.instances.bookService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.bookService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.bookService.event-consumer-buffer-size=10

# TimeLimiter
resilience4j.timelimiter.instances.bookService.timeout-duration=3s
resilience4j.timelimiter.instances.bookService.cancel-running-future=true

# RateLimiter
resilience4j.ratelimiter.instances.bookService.limit-for-period=5
resilience4j.ratelimiter.instances.bookService.limit-refresh-period=5s

# Retry
resilience4j.retry.instances.bookService.max-attempts=3
resilience4j.retry.instances.bookService.wait-duration=500ms
resilience4j.retry.instances.bookService.enable-exponential-backoff=true
resilience4j.retry.instances.bookService.exponential-backoff-multiplier=2

# Order-Service
resilience4j.circuitbreaker.instances.orderService.register-health-indicator=true
resilience4j.circuitbreaker.instances.orderService.sliding-window-size=10
resilience4j.circuitbreaker.instances.orderService.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.orderService.failure-rate-threshold=10
resilience4j.circuitbreaker.instances.orderService.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.orderService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.orderService.event-consumer-buffer-size=10

# TimeLimiter
resilience4j.timelimiter.instances.orderService.timeout-duration=2s
resilience4j.timelimiter.instances.orderService.cancel-running-future=false

# RateLimiter
resilience4j.ratelimiter.instances.orderService.limit-for-period=20
resilience4j.ratelimiter.instances.orderService.limit-refresh-period=1s

# Retry
resilience4j.retry.instances.orderService.max-attempts=2
resilience4j.retry.instances.orderService.wait-duration=2s
resilience4j.retry.instances.orderService.enable-exponential-backoff=true
resilience4j.retry.instances.orderService.exponential-backoff-multiplier=2

# Timeout TCP
spring.cloud.gateway.httpclient.response-timeout=12s

info.app.nome=Gateway-Services
info.app.versione=1.1.3
info.app.descrizione=Servizio di Gestione Geteway