spring.application.name=gateway-services
server.port=8089
spring.profiles.active=dev

spring.cloud.config.discovery.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.gateway.server.webmvc.enabled=true
spring.cloud.config.import-check.enabled=false

management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*
logging.structured.format.console=ecs
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]

spring.cloud.gateway.server.webmvc.routes[0].id=book-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api-book/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/api-book/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[0].filters[1]=CircuitBreaker=name=bookService,fallbackUri=forward:/api/fallback/book

spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api-orders/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/api-orders/(?<segment>.*), /${segment}
spring.cloud.gateway.server.webmvc.routes[1].filters[1]=CircuitBreaker=name=orderService,fallbackUri=forward:/api/fallback/order

resilience4j.circuitbreaker.instances.orderService.register-health-indicator=false
resilience4j.circuitbreaker.instances.bookService.register-health-indicator=false