spring.application.name=book-services
server.port=8085
spring.profiles.active=dev

spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=spring-config-book
spring.config.import=optional:configserver:http://localhost:8084

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
logging.level.org.hibernate.orm.results.loading=WARN

# Gestione ZipKim
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*

# Gestione di Implemetazione
resilience4j.circuitbreaker.instances.book-services.register-health-indicator=true
resilience4j.circuitbreaker.instances.book-services.sliding-window-size=3
resilience4j.circuitbreaker.instances.book-services.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.book-services.failure-rate-threshold=30
resilience4j.circuitbreaker.instances.book-services.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.book-services.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.book-services.event-consumer-buffer-size=10

# Gestione Rate-Limiter (Limite Chiamate)
resilience4j.ratelimiter.instances.book-services.limit-for-period=3
resilience4j.ratelimiter.instances.book-services.limit-refresh-period=10s
resilience4j.ratelimiter.instances.book-services.timeout-duration=0s

# Gestione Retry (Rintento del servizio)
resilience4j.retry.instances.book-services.max-attempts=3
resilience4j.retry.instances.book-services.wait-duration=2s
resilience4j.retry.instances.book-services.retry-exceptions=java.io.IOException,java.util.concurrent.TimeoutException
resilience4j.retry.instances.book-services.ignore-exceptions=java.lang.IllegalArgumentException