-- Table: public.libri

CREATE TABLE IF NOT EXISTS public.libri
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    titolo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    autore character varying(100) COLLATE pg_catalog."default" NOT NULL,
    editore character varying(100) COLLATE pg_catalog."default",
    anno_pubblicazione integer,
    isbn character varying(13) COLLATE pg_catalog."default",
    categoria character varying(50) COLLATE pg_catalog."default" DEFAULT 'Narrativa'::character varying,
    num_copie integer DEFAULT 1,
    disponibile integer DEFAULT 1,
    posizione_scaffale character varying(20) COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    prezzo numeric(10,2) NOT NULL,
    cover_color character varying(20) COLLATE pg_catalog."default",
    cover_img text COLLATE pg_catalog."default" DEFAULT 'Not Found'::character varying,
    CONSTRAINT libri_pkey PRIMARY KEY (id),
    CONSTRAINT libri_isbn_key UNIQUE (isbn),
    CONSTRAINT libri_anno_pubblicazione_check CHECK (anno_pubblicazione > 1000 AND anno_pubblicazione <= 2026),
    CONSTRAINT libri_disponibile_check CHECK (disponibile >= 0),
    CONSTRAINT libri_num_copie_check CHECK (num_copie > 0),
    CONSTRAINT libri_prezzo_check CHECK (prezzo > 0::numeric)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.libri
    OWNER to postgres;

-- Table: public.checkout

CREATE TABLE IF NOT EXISTS public.checkout
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ordine_id integer NOT NULL,
    libro_id integer NOT NULL,
    libro_prezzo numeric(10,2) NOT NULL,
    quantita integer NOT NULL DEFAULT 1,
    prezzo_subtotale numeric(10,2) NOT NULL,
    CONSTRAINT checkout_pkey PRIMARY KEY (id),
    CONSTRAINT uq_checkout_ordine_libro UNIQUE (ordine_id, libro_id),
    CONSTRAINT fk_checkout_libro FOREIGN KEY (libro_id)
        REFERENCES public.libri (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_checkout_ordine FOREIGN KEY (ordine_id)
        REFERENCES public.ordini (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT checkout_libro_prezzo_check CHECK (libro_prezzo > 0::numeric),
    CONSTRAINT checkout_prezzo_subtotale_check CHECK (prezzo_subtotale > 0::numeric),
    CONSTRAINT checkout_quantita_check CHECK (quantita > 0)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.checkout
    OWNER to postgres;

-- Table: public.ordini

CREATE TABLE IF NOT EXISTS public.ordini
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    prezzo_totale numeric(10,2),
    ordinato boolean DEFAULT false,
    CONSTRAINT ordini_pkey PRIMARY KEY (id),
    CONSTRAINT ordini_prezzo_totale_check CHECK (prezzo_totale >= 0::numeric)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ordini
    OWNER to postgres;

-- Table: public.recensioni

CREATE TABLE IF NOT EXISTS public.recensioni
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    libro_id integer NOT NULL,
    descrizione character varying(500) COLLATE pg_catalog."default" DEFAULT 'Vuoto'::character varying,
    voto integer DEFAULT 0,
    "check" boolean DEFAULT false,
    CONSTRAINT recensioni_pkey PRIMARY KEY (id),
    CONSTRAINT fk_recensioni_libro FOREIGN KEY (libro_id)
        REFERENCES public.libri (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recensioni
    OWNER to postgres;

-- FK recensioni.libro_id -> libri.id (ON DELETE CASCADE)

ALTER TABLE recensioni
DROP CONSTRAINT fk_recensioni_libro,
ADD CONSTRAINT fk_recensioni_libro
  FOREIGN KEY (libro_id) REFERENCES libri(id)
  ON DELETE CASCADE;